#!/usr/bin/bash

#Define the directories to backup
Directories=(/etc /home /var/www)

#Define the backup file name
Backup_file="backup-$(date +%Y-%m-%d).tar.gz"

#Create the backup
tar -czf $Backup_file ${Directories[@]}

#Print conformation
echo "Backup created: $Backup_file"
